kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-ro
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-ro
subjects:
- kind: Group
  namespace: web
  name: 7e9c09c7-cc97-43f3-a3fa-92c84a27b4d0 #api-dev