kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources:
  - jobs
  - cronjobs
  - pods
  - svc
  - events
  - logs
  verbs: ["*"]