kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-full-access
  namespace: api
rules:
- apiGroups: ["api-dev"]
  resources:
  - jobs
  - cronjobs
  - pods
  - svc
  - events
  - logs
  verbs: ["*"]