kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-full-access
  namespace: web
rules:
- apiGroups: ["web-dev"]
  resources:
  - jobs
  - cronjobs
  - pods
  - svc
  - events
  verbs: ["*"]