kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev
subjects:
- kind: Group
  namespace: api
  name: 7e9c09c7-cc97-43f3-a3fa-92c84a27b4d0