kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-ro
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources:
  - jobs
  - cronjobs
  - pods
  - svc
  - events
  - logs
  verbs: ["get", "list", "watch"]