apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- tripviewer-deploy.yaml
- tripviewer-service.yaml
 
namespace: web
 
images:
  - name: tripviewer-image
    newTag: "1"
    newName: registrywqs1862.azurecr.io/tripviewer
