apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80