kind: Deployment
apiVersion: apps/v1
metadata:
  name: poi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
        tier: frontend
    spec:
      containers:
        - name: poi
          image: poi-image
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: poi-secrets          
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


