kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-java-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
        tier: backend
    spec:
      containers:
        - name: user-java
          image: user-java-image
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
          - secretRef:
             name: poi-secrets         
      restartPolicy: Always
      volumes:
        - name: poi-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
