kind: Deployment
apiVersion: apps/v1
metadata:
  name: userprofile-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
        tier: backend
    spec:
      containers:
        - name: userprofile
          image: userprofile-image
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
          - secretRef:
             name: poi-secrets          
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


