kind: Deployment
apiVersion: apps/v1
metadata:
  name: trips-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
        tier: backend
    spec:
      containers:
        - name: trips
          image: trips-image
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
          - secretRef:
             name: poi-secrets
          env:
          - name: OPENAPI_DOCS_URI
            value: "http://changeme"
          - name:  DEBUG_LOGGING
            value: "false"
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


